import type { Metadata } from "next";
import Link from "next/link";
import { pageGraph, breadcrumbs } from "../_components/schema";
import { biz } from "../_components/site-data";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms of Service for the Trade Business website — informational use, enquiries, and site rules.",
  alternates: { canonical: "/terms" },
};

/** Generated by scripts/generate-legal-pages.mjs — Termageddon-class depth, inventory-honest. */
export default function Page() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(pageGraph("/terms", "Terms of Service | " + biz.name)),
        }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(
            breadcrumbs([
              { name: "Home", href: "/" },
              { name: "Terms of Service", href: "/terms" },
            ])
          ),
        }}
      />
      <main className="bg-surface-1">
        <div className="mx-auto max-w-3xl px-5 py-16 lg:px-8 lg:py-24">
          <nav className="font-body mb-8 flex items-center gap-2 text-sm text-ink-muted" aria-label="Breadcrumb">
            <Link href="/" className="hover:text-accent-text">Home</Link>
            <span aria-hidden="true">/</span>
            <span className="text-ink">Terms of Service</span>
          </nav>
          <header className="mb-12 border-b border-surface-3 pb-8" data-reveal>
            <p className="font-body text-xs font-semibold uppercase tracking-[0.2em] text-accent-text">Legal</p>
            <h1 className="font-display mt-3 text-4xl font-bold text-ink sm:text-5xl">Terms of Service</h1>
            <p className="font-body mt-4 text-sm text-ink-muted">Effective date: August 22, 2026</p>
            <p className="font-body mt-1 text-sm text-ink-muted">Trade Business · Town, State</p>
          </header>
          <div className="space-y-12">
          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Agreement to these terms</h2>
            <p className="font-body text-ink-muted leading-relaxed">These Terms of Service ("Terms") govern your use of the website operated for Trade Business (the "Site"). By accessing or using the Site, you agree to these Terms.</p>
            <p className="font-body text-ink-muted leading-relaxed">If you do not agree, do not use the Site. These Terms are meant to match the depth of a professional small-business policy pack (Termageddon / Squarespace class), written for this Site specifically.</p>
            <p className="font-body text-ink-muted leading-relaxed">Effective date: August 22, 2026.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">The business and the Site</h2>
            <p className="font-body text-ink-muted leading-relaxed">Trade Business operates this Site to describe services in the Town area (Serving the local area) and to make it easy to get in touch.</p>
            <p className="font-body text-ink-muted leading-relaxed">Published contact details: (555) 555-0100 or hello@example.com; 123 Main St, Town, ST, 00000.</p>
            <p className="font-body text-ink-muted leading-relaxed">The Site is a marketing and information website. It is not an online storefront that completes paid checkout for field work unless a page clearly says otherwise.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Informational purpose — not a contract</h2>
            <p className="font-body text-ink-muted leading-relaxed">Content on the Site — including service descriptions, photos, example pricing mentions, blogs, and FAQs — is for general information.</p>
            <p className="font-body text-ink-muted leading-relaxed">Nothing on the Site is, by itself, a binding quote, a fixed-price offer, an insurance certificate, a license filing, or a contract for work. Any job is agreed separately when the business confirms scope, timing, and price with you.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Enquiries, forms, calls, and chat</h2>
            <p className="font-body text-ink-muted leading-relaxed">Submitting a form, starting a chat, calling, or texting is a request to be contacted. It does not reserve a crew and does not lock pricing.</p>
            <p className="font-body text-ink-muted leading-relaxed">We may refuse or reschedule work when a site visit shows unsafe conditions, access problems, or a scope that differs from what was described online.</p>
            <p className="font-body text-ink-muted leading-relaxed">Chat answers are automated assistance for common questions. They can be incomplete. For urgent issues (active flooding, electrical hazards, or similar), call the business directly.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Services and service area</h2>
            <p className="font-body text-ink-muted leading-relaxed">Service menus, hours, and coverage areas on the Site are published as of the Effective date and can change without updating every historical page at once.</p>
            <p className="font-body text-ink-muted leading-relaxed">Some jobs require licenses, permits, or manufacturer constraints. Online copy cannot list every constraint for every property. Confirm requirements during your consultation.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Photos, media, and examples</h2>
            <p className="font-body text-ink-muted leading-relaxed">Photos and video on the Site illustrate the kind of work associated with the business. Lighting, landscaping, structure, and finishes differ by property.</p>
            <p className="font-body text-ink-muted leading-relaxed">Before-and-after or gallery images are examples, not a promise of identical results.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Intellectual property</h2>
            <p className="font-body text-ink-muted leading-relaxed">Site design, original text produced for this Site, and original graphics we publish are protected by applicable intellectual property laws. You may not copy the Site wholesale for commercial reuse without permission.</p>
            <p className="font-body text-ink-muted leading-relaxed">You may share links to public pages. You may not scrape the Site for bulk republishing, train models on the Site in a way that violates applicable law, or frame the Site so it appears to be yours.</p>
            <p className="font-body text-ink-muted leading-relaxed">Third-party marks (product names, platforms) belong to their owners.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Acceptable use</h2>
            <p className="font-body text-ink-muted leading-relaxed">You agree not to:</p>
            <ul className="font-body list-disc space-y-2 pl-5 text-ink-muted leading-relaxed">
              <li>Use the Site for unlawful purposes or to harass staff or other users.</li>
              <li>Attempt to break, overload, or probe the Site or its chat/form endpoints without authorization.</li>
              <li>Submit malware, spam, or deceptive content through forms or chat.</li>
              <li>Impersonate another person when requesting service.</li>
              <li>Harvest phone numbers or emails from the Site for unrelated bulk outreach.</li>
            </ul>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Third-party links and tools</h2>
            <p className="font-body text-ink-muted leading-relaxed">The Site may link to maps, payment processors, social networks, or suppliers. Those services have their own terms. We are not responsible for their content or practices.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Disclaimer of warranties</h2>
            <p className="font-body text-ink-muted leading-relaxed">THE SITE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS TO THE FULLEST EXTENT PERMITTED BY LAW. WE DISCLAIM WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT AS THEY APPLY TO THE SITE CONTENT.</p>
            <p className="font-body text-ink-muted leading-relaxed">We do not warrant that the Site will be uninterrupted, error-free, or free of harmful components. Field services, when separately agreed, are handled under that separate understanding with you — not under website marketing copy alone.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Limitation of liability</h2>
            <p className="font-body text-ink-muted leading-relaxed">TO THE FULLEST EXTENT PERMITTED BY LAW, Trade Business AND ITS OWNERS AND STAFF WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SITE OR RELIANCE ON SITE CONTENT.</p>
            <p className="font-body text-ink-muted leading-relaxed">Some jurisdictions do not allow certain limitations. In those places, our liability is limited to the maximum extent allowed. This section applies to the website experience; separately contracted field work may carry different terms stated in a written estimate or agreement.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Privacy</h2>
            <p className="font-body text-ink-muted leading-relaxed">Our Privacy Policy explains how we handle personal information collected through the Site. By using the Site, you also acknowledge that policy.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Governing law</h2>
            <p className="font-body text-ink-muted leading-relaxed">These Terms are governed by the laws of State, without regard to conflict-of-law rules that would choose another jurisdiction’s law.</p>
            <p className="font-body text-ink-muted leading-relaxed">We do not name a specific courthouse venue here. If a dispute arises, the parties will use the courts and procedures available under applicable law.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Changes to these Terms</h2>
            <p className="font-body text-ink-muted leading-relaxed">We may update these Terms when the Site or our practices change. The Effective date will change when we do. If you continue using the Site after an update, you should read the revised Terms.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Severability and entire agreement</h2>
            <p className="font-body text-ink-muted leading-relaxed">If a court finds a part of these Terms unenforceable, the rest remains in effect. These Terms and the Privacy Policy are the website terms between you and us regarding Site use. They do not replace a signed work order, estimate, or contract for field services.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Contact</h2>
            <p className="font-body text-ink-muted leading-relaxed">Questions about these Terms: (555) 555-0100 or hello@example.com.</p>
            <p className="font-body text-ink-muted leading-relaxed">This page was prepared from the details Trade Business publishes about itself. If anything needs changing, email hello@example.com and it will be updated.</p>
            <p className="font-body text-ink-muted leading-relaxed">Trade Business · (555) 555-0100 · hello@example.com.</p>
          </section>
          </div>
        </div>
      </main>
    </>
  );
}
