import type { Metadata } from "next";
import Link from "next/link";
import { pageGraph, breadcrumbs } from "../_components/schema";
import { biz } from "../_components/site-data";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Privacy Policy for Trade Business — how this website collects, uses, and shares information.",
  alternates: { canonical: "/privacy" },
};

/** Generated by scripts/generate-legal-pages.mjs — Termageddon-class depth, inventory-honest. */
export default function Page() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(pageGraph("/privacy", "Privacy Policy | " + biz.name)),
        }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(
            breadcrumbs([
              { name: "Home", href: "/" },
              { name: "Privacy Policy", href: "/privacy" },
            ])
          ),
        }}
      />
      <main className="bg-surface-1">
        <div className="mx-auto max-w-3xl px-5 py-16 lg:px-8 lg:py-24">
          <nav className="font-body mb-8 flex items-center gap-2 text-sm text-ink-muted" aria-label="Breadcrumb">
            <Link href="/" className="hover:text-accent-text">Home</Link>
            <span aria-hidden="true">/</span>
            <span className="text-ink">Privacy Policy</span>
          </nav>
          <header className="mb-12 border-b border-surface-3 pb-8" data-reveal>
            <p className="font-body text-xs font-semibold uppercase tracking-[0.2em] text-accent-text">Legal</p>
            <h1 className="font-display mt-3 text-4xl font-bold text-ink sm:text-5xl">Privacy Policy</h1>
            <p className="font-body mt-4 text-sm text-ink-muted">Effective date: August 22, 2026</p>
            <p className="font-body mt-1 text-sm text-ink-muted">Trade Business · Town, State</p>
          </header>
          <div className="space-y-12">
          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Introduction</h2>
            <p className="font-body text-ink-muted leading-relaxed">This Privacy Policy describes how Trade Business ("Trade Business", "we", "us", or "our") collects, uses, and shares information when you visit this website, contact us, or use features on the site such as forms or chat.</p>
            <p className="font-body text-ink-muted leading-relaxed">We wrote this policy for this specific website. It is meant to read like the policies you see on a professional small-business site (the same class of document tools such as Termageddon and Squarespace produce), while staying accurate about what this site actually does.</p>
            <p className="font-body text-ink-muted leading-relaxed">Effective date: August 22, 2026. If we change how the site handles information in a material way, we will update this page and the date above.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Who we are</h2>
            <p className="font-body text-ink-muted leading-relaxed">Trade Business is a local trade business serving customers in and around Town (Serving the local area). Published contact details: 123 Main St, Town, ST, 00000.</p>
            <p className="font-body text-ink-muted leading-relaxed">For privacy questions, contact us at (555) 555-0100 or hello@example.com.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Scope of this policy</h2>
            <p className="font-body text-ink-muted leading-relaxed">This policy applies to information collected through this website and through communications that start from this website (for example, a form submission, a phone call to the number listed here, or an email to the address listed here).</p>
            <p className="font-body text-ink-muted leading-relaxed">It does not cover websites we do not control, including map providers, social networks, or review platforms you may reach through outbound links.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Information we collect</h2>
            <p className="font-body text-ink-muted leading-relaxed">We collect information in these categories when you choose to provide it or when it is necessary to operate the site:</p>
            <ul className="font-body list-disc space-y-2 pl-5 text-ink-muted leading-relaxed">
              <li>Identifiers and contact details you choose to give us (name, phone number, email address, service address or city).</li>
              <li>The contents of messages you send (form notes, chat text, or email body).</li>
              <li>Service preferences you select (for example, a service type on a contact form).</li>
              <li>Technical details needed to deliver a form submission (such as the page you were on and basic browser information the network request carries).</li>
              <li>Chat conversation turns you send to the on-site assistant, and your IP address for rate-limiting the chat service.</li>
              <li>Call or text metadata when you contact the published business phone number (handled by your carrier and our phone system, not stored as a marketing profile on this static website).</li>
            </ul>
            <p className="font-body text-ink-muted leading-relaxed">We do not ask for Social Security numbers, payment card numbers, or government ID through this website. Please do not send that information by form or chat.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Sources of information</h2>
            <p className="font-body text-ink-muted leading-relaxed">We obtain information from:</p>
            <ul className="font-body list-disc space-y-2 pl-5 text-ink-muted leading-relaxed">
              <li>Directly from you when you fill out a form, use chat, email us, or call us.</li>
              <li>From your device as part of ordinary web requests (for example, IP address seen by our host when a page or form is requested).</li>
            </ul>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">How we use information</h2>
            <p className="font-body text-ink-muted leading-relaxed">We use the information above to:</p>
            <ul className="font-body list-disc space-y-2 pl-5 text-ink-muted leading-relaxed">
              <li>Respond to requests for estimates, service, or information.</li>
              <li>Schedule visits and follow up by phone, text, or email when you asked to be contacted.</li>
              <li>Operate, secure, and troubleshoot this website.</li>
              <li>Provide automated answers about services, hours, and service area through the on-site chat assistant.</li>
              <li>Comply with law when we are legally required to do so.</li>
            </ul>
            <p className="font-body text-ink-muted leading-relaxed">We do not sell your personal information, and we do not use this website to run advertising audiences or cross-context behavioral ads.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">How we share information</h2>
            <p className="font-body text-ink-muted leading-relaxed">We share information only as needed to run the business and this website:</p>
            <ul className="font-body list-disc space-y-2 pl-5 text-ink-muted leading-relaxed">
              <li>People at the business who need the enquiry to reply or schedule work.</li>
              <li>Hosting and form-delivery infrastructure that moves your submission from the website to the business (the same way any professionally hosted contact form works).</li>
              <li>The chat service that powers the on-site assistant, including an AI model provider that generates replies from the conversation turns you send. If you leave a name plus a phone or email in chat, that may be passed along as a lead so someone can follow up.</li>
              <li>Professional advisors or authorities when required by law or to protect rights and safety.</li>
            </ul>
            <p className="font-body text-ink-muted leading-relaxed">We do not sell personal information to data brokers. We do not share personal information for cross-context behavioral advertising.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">On-site chat and AI assistant</h2>
            <p className="font-body text-ink-muted leading-relaxed">This website includes a chat widget. When you use it, the text you type is sent to our chat service so an assistant can reply. Recent turns in the conversation travel with each request so the assistant has context.</p>
            <p className="font-body text-ink-muted leading-relaxed">Replies are generated with the help of an AI service. Chat is for general questions about services, hours, and service area. It is not a substitute for a licensed inspection, a formal quote, or emergency dispatch.</p>
            <p className="font-body text-ink-muted leading-relaxed">Do not send payment card numbers, passwords, or sensitive medical or government identifiers through chat. If you provide a name and a phone number or email, we may treat that as a request for a human follow-up.</p>
            <p className="font-body text-ink-muted leading-relaxed">Your IP address may be used to limit abuse of the chat endpoint. Conversations are not published on the website.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Contact forms and email links</h2>
            <p className="font-body text-ink-muted leading-relaxed">The contact form on this site sends the details you enter to the business so we can respond. Submissions are handled as service enquiries, not as a newsletter signup, unless a page clearly offers a separate subscription.</p>
            <p className="font-body text-ink-muted leading-relaxed">Some links open your own email application addressed to the business. In that case the message is sent from your mail account; the website itself does not store the email body.</p>
            <p className="font-body text-ink-muted leading-relaxed">Required fields exist so we can reply. Optional fields help us understand the job. You can call instead of using the form.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Cookies, analytics, and tracking</h2>
            <p className="font-body text-ink-muted leading-relaxed">This website is built as a static marketing site. It does not install advertising pixels, and it does not load third-party analytics packages such as Google Analytics, Meta Pixel, Hotjar, or similar tools.</p>
            <p className="font-body text-ink-muted leading-relaxed">We do not set first-party tracking cookies for advertising, and we do not use local or session storage to track you across visits for marketing.</p>
            <p className="font-body text-ink-muted leading-relaxed">Your browser may still send ordinary request data (IP address, user agent) to our host when you load pages. That is standard for any website.</p>
            <p className="font-body text-ink-muted leading-relaxed">If a page plays a hosted video, your browser requests the video file from our host the same way it requests images.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">How long we keep information</h2>
            <p className="font-body text-ink-muted leading-relaxed">Enquiry information is kept as long as needed to respond to you, perform the work you requested, meet bookkeeping or legal duties, and resolve disputes.</p>
            <p className="font-body text-ink-muted leading-relaxed">We do not publish a fixed multi-year retention schedule on this page because office practices can change. If you want a specific enquiry deleted from our active follow-up lists, contact us and we will handle the request as the law allows.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Security</h2>
            <p className="font-body text-ink-muted leading-relaxed">We use reputable hosting and transport encryption (HTTPS) for this website. No method of transmission or storage is completely secure. Please use judgment about what you send through forms or chat.</p>
            <p className="font-body text-ink-muted leading-relaxed">If we learn of a breach that affects your personal information in a way that requires notice under applicable law, we will notify you as required.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Your choices and rights</h2>
            <p className="font-body text-ink-muted leading-relaxed">You can ask us what contact information we hold about you from website enquiries, ask us to correct it, or ask us to stop routine follow-up marketing messages where applicable.</p>
            <p className="font-body text-ink-muted leading-relaxed">To make a request, email hello@example.com or call (555) 555-0100 and describe what you need. We may need to verify that we are speaking with the right person.</p>
            <p className="font-body text-ink-muted leading-relaxed">Depending on where you live, privacy laws in State or other jurisdictions may give you additional rights. This policy does not list every statute by section number. If you believe you have a specific legal right, contact us and we will respond in good faith.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Children</h2>
            <p className="font-body text-ink-muted leading-relaxed">This website is intended for adults arranging trade services. It is not directed to children under 13, and we do not knowingly collect personal information from children under 13. If you believe a child provided information through this site, contact us and we will delete it.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Third-party sites and services</h2>
            <p className="font-body text-ink-muted leading-relaxed">Our pages may link to maps, social profiles, review listings, or other third-party sites. Their privacy practices are governed by their own policies. We are not responsible for those sites.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Do Not Track</h2>
            <p className="font-body text-ink-muted leading-relaxed">Some browsers offer a Do Not Track signal. Because this site does not run advertising trackers, there is no additional advertising response layered on top of that signal. You can still use browser controls to block third-party cookies globally.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Changes to this policy</h2>
            <p className="font-body text-ink-muted leading-relaxed">We may update this Privacy Policy when the website or our practices change. The Effective date at the top will change when we do. Continued use of the site after an update means you should read the revised policy.</p>
            <p className="font-body text-ink-muted leading-relaxed">This page was prepared from the details Trade Business publishes about itself and from what this website’s code actually does. If something is wrong, email hello@example.com and it will be corrected.</p>
          </section>

          <section className="space-y-4" data-reveal>
            <h2 className="font-display text-2xl font-bold text-ink">Contact us</h2>
            <p className="font-body text-ink-muted leading-relaxed">Trade Business</p>
            <p className="font-body text-ink-muted leading-relaxed">123 Main St, Town, ST, 00000</p>
            <p className="font-body text-ink-muted leading-relaxed">Phone: (555) 555-0100</p>
            <p className="font-body text-ink-muted leading-relaxed">Email: hello@example.com</p>
            <p className="font-body text-ink-muted leading-relaxed">Ask for privacy or website questions when you reach out so we can route your message quickly.</p>
          </section>
          </div>
        </div>
      </main>
    </>
  );
}
